# Generated by Django 4.0.3 on 2022-05-21 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address_admin_ambulance_ambulanceservice_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcarefacility',
            old_name='descriptioni',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='healthcareservice',
            old_name='HealthCareFacilityID',
            new_name='healthCareFacilityID',
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
