# Generated by Django 4.0.4 on 2022-06-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcarefacility',
            name='name',
            field=models.TextField(),
        ),
    ]
