# Generated by Django 4.0.4 on 2022-05-30 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='healthProfileID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthprofile'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreview',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='accountID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthfacilityaccount'),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='healthFacilityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ambulanceservice'),
        ),
        migrations.AlterField(
            model_name='ambulanceservice',
            name='accountID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthcarefacility'),
        ),
        migrations.AlterField(
            model_name='ambulanceservice',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.admin'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='healthFacilityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthcarefacility'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='healthFacilityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthcarefacility'),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='accountID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthfacilityaccount'),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.admin'),
        ),
        migrations.AlterField(
            model_name='healthcareservice',
            name='healthCareFacilityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthcarefacility'),
        ),
        migrations.AlterField(
            model_name='healthfacilityaccount',
            name='healthFacilityOrAmbulanceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ambulanceservice'),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='UserReviewID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userreview'),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='commenterID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userrating'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='healthFacilityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthcarefacility'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='healthFacilityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthcarefacility'),
        ),
    ]
