# Generated by Django 4.0.4 on 2022-06-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_healthcarefacility_gpscoordinates_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
