# Generated by Django 4.0.4 on 2022-05-30 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment_userid_user_address_user_healthprofileid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcareservice',
            name='Row3',
        ),
        migrations.AlterField(
            model_name='ambulanceservice',
            name='imageGallery',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='imageGallery',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='healthfacilityaccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='HealthFacilityAccountImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('HealthFacilityAccountID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthfacilityaccount')),
            ],
        ),
    ]
