# Generated by Django 4.0.4 on 2022-05-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('ad', 'Admin'), ('h', 'HealthFacility'), ('am', 'Ambulance'), ('u', 'User')], default=3, null=True),
        ),
    ]
