# Generated by Django 4.0.4 on 2022-06-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220619_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='healthFacilityType',
        ),
    ]
