# Generated by Django 4.0.4 on 2022-05-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_healthcareservice_row3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacilityaccount',
            name='logo',
            field=models.ImageField(blank=True, default='defaultHealthFacility.png', null=True, upload_to=''),
        ),
    ]
