# Generated by Django 4.0.4 on 2022-06-18 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_healthcarefacility_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='healthFacilityID',
            new_name='healthFacility',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='healthFacilityType',
        ),
        migrations.AddField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
