# Generated by Django 4.0.4 on 2022-06-11 01:47

import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_address_alter_healthcarefacility_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrating',
            old_name='healthFacilityID',
            new_name='healthFacility',
        ),
        migrations.RemoveField(
            model_name='healthcarefacility',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='healthcarefacility',
            name='imageGallery',
        ),
        migrations.RemoveField(
            model_name='healthcarefacility',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='healthcarefacility',
            name='source',
        ),
        migrations.RemoveField(
            model_name='healthcarefacility',
            name='verificationStatus',
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='faxNumbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='foundedIn',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='imageGalleryLinks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='imageGalleryPhotos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='numberOfEmployeesRange',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=2),
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='phoneNumbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='source_addedBy',
            field=models.CharField(choices=[('SC', 'Scraper'), ('US', 'User'), ('AD', 'Admin')], default='SC', max_length=2),
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='source_identifier',
            field=models.TextField(default='ethyp'),
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='total_ratings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='verificationIndexPer10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='averageNumberOfUsers',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='doctorCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
