# Generated by Django 4.0.4 on 2022-06-18 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_healthfacilityid_userreview_healthfacility_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcarefacility',
            old_name='total_ratings',
            new_name='totalRatings',
        ),
        migrations.AlterField(
            model_name='userrating',
            name='creationDateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='lastUpdateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
