# Generated by Django 4.0.4 on 2022-06-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_emergencycontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontacts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
