# Generated by Django 4.0.4 on 2022-06-11 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_healthfacilityid_userrating_healthfacility_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcarefacility',
            old_name='type',
            new_name='facility_type',
        ),
    ]
