# Generated by Django 4.0.4 on 2022-06-19 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userreview_healthfacilitytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='creationDateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='lastUpdateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='review',
            field=models.TextField(),
        ),
    ]
