# Generated by Django 4.0.4 on 2022-05-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_healthfacilityaccount_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacilityaccount',
            name='logo',
            field=models.ImageField(blank=True, default='defaultHealthFacility.jpg', null=True, upload_to=''),
        ),
    ]
