# Generated by Django 4.0.4 on 2022-06-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_type_healthcarefacility_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcarefacility',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
