# Generated by Django 4.0.4 on 2022-05-30 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_healthfacilityaccount_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCareFacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='healthfacilityaccountimage',
            name='HealthFacilityAccountID',
        ),
        migrations.RemoveField(
            model_name='healthcarefacility',
            name='accountID',
        ),
        migrations.RemoveField(
            model_name='healthcarefacility',
            name='imageGallery',
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='logo',
            field=models.ImageField(blank=True, default='defaultHealthFacility.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, default='defaultUser.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='accountID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthcarefacility'),
        ),
        migrations.DeleteModel(
            name='HealthFacilityAccount',
        ),
        migrations.DeleteModel(
            name='HealthFacilityAccountImage',
        ),
        migrations.AddField(
            model_name='healthcarefacilityimage',
            name='HealthFacilityAccountID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthcarefacility'),
        ),
    ]
