# Generated by Django 4.0.4 on 2022-06-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_healthfacilityid_userreview_healthfacility_and_more'),
        ('api', '0006_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
    ]
