# Generated by Django 4.0.4 on 2022-06-18 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20220618_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcarefacility',
            name='accountID',
        ),
        migrations.RemoveField(
            model_name='healthcarefacility',
            name='additionalAttributes',
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='creationDateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='lastUpdateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
