# Generated by Django 4.0.4 on 2022-06-18 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_healthcarefacility_accountid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcarefacility',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
