# Generated by Django 4.0.4 on 2022-06-18 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_healthcarefacility_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='requesterAccount',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
