# Generated by Django 4.0.4 on 2022-06-11 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_healthcarefacility_creationdatetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcarefacility',
            old_name='imageGalleryLinks',
            new_name='imageGallaryLinks',
        ),
        migrations.RenameField(
            model_name='healthcarefacility',
            old_name='imageGalleryPhotos',
            new_name='imageGallaryPhotos',
        ),
    ]
