# Generated by Django 4.0.4 on 2022-06-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_claimrequest_requesteraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
