# Generated by Django 4.0.4 on 2022-06-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_claimrequest_isdone'),
        ('api', '0012_auto_20220618_2213'),
    ]

    operations = [
    ]
