# Generated by Django 4.0.4 on 2022-06-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20220618_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequest',
            name='cancelDateTime',
        ),
    ]
