# Generated by Django 4.0.4 on 2022-06-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_claimrequest_canceldatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='requesterPhoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
