# Generated by Django 4.0.4 on 2022-06-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_claimrequest_requesterphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
