# Generated by Django 4.0.4 on 2022-06-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_claimrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='claim_attachments/'),
        ),
    ]
