# Generated by Django 4.0.4 on 2022-06-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_claimrequest_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequest',
            name='status',
        ),
    ]
