# Generated by Django 4.0.4 on 2022-06-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_claimrequest_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createdBy',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='modifiedBy',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
