# Generated by Django 4.0.4 on 2022-06-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_user_createdby_alter_user_modifiedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modifiedBy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modifiedDate',
        ),
    ]
